<a href="https://colab.research.google.com/github/depeshsikarwar/Data-Science/blob/main/lec04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np

In [13]:
# In array inside a bool function it is number and always true
# string is a value
a=np.array([1,2,3,4,0,'HELLO',8])
print(a[-1])
print(bool(a[-1]))
a1=np.array([1,2,3,4,0,'HELLO',False])
print(a1[-1])
print(bool(a1[-1]))

8
True
False
True


In [14]:
a=False
print(bool(0))

False


In [25]:
a=np.zeros(3)
b=np.zeros((3,4))
c=np.zeros((3,4,5))
d=np.zeros((1,1,1,1,1,1,1,1,1,1,1,1,1))
# print(d)
print(c)
print(type(c[0][0][0]))
# print()
# print()
# print(b)
# print()
# print()
# print(a)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
<class 'numpy.float64'>


In [31]:
c=np.zeros((3,4,5),dtype=int)
d=np.ones((3,4,5),dtype=int)
print(d)
# print(c)


[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [28]:
a=np.empty(4,dtype=int)
print(a)
b=np.full(4,5,dtype=int)
print(b)

[1097986210          0          0          0]
[5 5 5 5]


In [48]:
a=np.arange(6,1,-4,dtype=int)
b=np.arange(1,10,2,dtype=int)
print(b)
print(a)

[1 3 5 7 9]
[6 2]


In [46]:
a=np.linspace(1,10,8,dtype=int)
b=np.linspace(1,10,2,endpoint=False,dtype=int)
print(b)
# endpoint=false is to exclude last digit
# (start,end,number of value)
print(a)

[1 5]
[ 1  2  3  4  6  7  8 10]


In [62]:
a=np.array([1,2,3,4,5,6,7,9,10])
print(np.size(a))
print(np.shape(a))
print(a.dtype)
# random.randint(start,end,number of value)select random value in between the range
# random.choice(array) select random value from array random.choice([2,4,2,9],2)choice two random value from the list
print(np.random.randint(a))
print(np.random.choice(a))

9
(9,)
int64
[0 0 0 0 1 1 1 7 6]
10


In [83]:
# BROADCASTING
a=np.random.randint(0,10,8)
b=np.random.randint(0,10,8)
print(a)
print(b)
# print(a*2)
# print(a+b)
# print(a-b)
# print(a*b)
# print(a/b)
# print(a%b)
# print(a**b)
# print(a//b)
# scaler se multiply so it is apply on every element

print([1,2,3,4,5,6,7]*2)
print([1,2,3,4]+[5,6,7,8])

[8 5 2 7 8 4 1 0]
[5 8 1 5 8 5 9 4]
[1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7]
[1, 2, 3, 4, 5, 6, 7, 8]


In [110]:
a=np.random.randint(1,15,8)
e=np.random.randint(1,15,8)
print(a)
print(e)
b=a.reshape(8,1)
print(b)
c=b.transpose()
print(c)
d=np.concatenate((a.reshape(-1, 1),e.reshape(-1, 1)),axis=1)
d=np.concatenate((a,e),axis=0)
print(d)

[ 6  5 14  4 14  8  3 11]
[12  2  4 14  3  6 10  5]
[[ 6]
 [ 5]
 [14]
 [ 4]
 [14]
 [ 8]
 [ 3]
 [11]]
[[ 6  5 14  4 14  8  3 11]]
[ 6  5 14  4 14  8  3 11 12  2  4 14  3  6 10  5]


In [113]:
a=np.random.randint(1,15,8)
b=np.random.randint(1,15,8)
c=np.where(b>a,b,a)
d=np.where(a>b,b,a)
e=np.where(a==b,b,a)
f=np.where(b>2,b,a)
# apply on each value
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

[ 9  1  9  6 11 11 10  8]
[10  8  7 11  9  1  2 14]
[10  8  9 11 11 11 10 14]
[9 1 7 6 9 1 2 8]
[ 9  1  9  6 11 11 10  8]
[10  8  7 11  9 11 10 14]


In [122]:
a=np.random.randint(1,15,8)
b=np.random.randint(1,15,8)
c=np.where(b>a,b,a)
d=np.sort(a)
print(a)
print(d)
print(b)

print(np.sum([a,b]))
print(np.mean(a))
print(np.mean([a,b]))
print(np.std(a))
print(np.std([a,b]))
print(np.var(a))
print(np.var([a,b]))
print(np.min(a))
print(np.max(a))
print(np.unique(a))


[ 4  7  2 13  4 11 12 11]
[ 2  4  4  7 11 11 12 13]
[7 2 1 6 6 9 1 7]
103
8.0
6.4375
4.0
3.823753881985607
16.0
14.62109375
2
13
[ 2  4  7 11 12 13]


In [124]:
lst=[]
for i in range(7):
  a=int(input("Enter the day score: "))
  lst.append(a)
arr=np.array(lst)
print("MIN: ",np.min(arr))
print("MAX: ",np.max(arr))
print("SUM: ",np.sum(arr))
print("MEAN: ",np.mean(arr))
print("UNIQUE: ",np.unique(arr))



Enter the day. score: 13
Enter the day. score: 15
Enter the day. score: 23
Enter the day. score: 56
Enter the day. score: 12
Enter the day. score: 32
Enter the day. score: 21
MIN:  12
MAX:  56
SUM:  172
24.571428571428573
[12 13 15 21 23 32 56]
