<a href="https://colab.research.google.com/github/depeshsikarwar/Data-Science/blob/main/lec05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [6]:
market=[1,2,3,4,5,6,7]
price=[40,50,60,70,80,90,100]
j=np.array(price)
k=np.min(j)
f=np.mean(j)
e=np.sum(j)
g=np.max(j)
print(j)
print(k)
print(f)
print(e)
print(g)



[ 40  50  60  70  80  90 100]
40
70.0
490
100


In [20]:
# Question 5
a=np.random.randint(1,91,(5,5));
print(a)
print()
b=a.mean(axis=1, dtype=int)
print("Mean of column:",b)
print()
c=a.mean(axis=0,dtype=int)
print("Mean of row:",c)
print()
d=a.max(axis=1)
print("Max in row:",d)
print()
e=a.min(axis=0)
print("MIN in column:",e)
print()
print("converted to negative:")
for i in range(5):
  for j in range(5):
    if(a[i][j]%2==0):
        a[i][j]=-1;

print(a)
print()
f=a.sum(axis=0)
print("sum of row:",f)
g=a.sum(axis=1)
print()
print("sum of column:",g)
count=0
for i in range(5):
  for j in range(5):
    if(a[i][j]<0):
      count=count+1;
print("Count of negative:",count)


[[54 75  9 38 74]
 [55 69 86 16 36]
 [76 58 59 32  4]
 [66 45 11 59 87]
 [45  7 68 35 20]]

Mean of column: [50 52 45 53 35]

Mean of row: [59 50 46 36 44]

Max in row: [75 86 76 87 68]

MIN in column: [45  7  9 16  4]

converted to negative:
[[-1 75  9 -1 -1]
 [55 69 -1 -1 -1]
 [-1 -1 59 -1 -1]
 [-1 45 11 59 87]
 [45  7 -1 35 -1]]

sum of row: [ 97 195  77  91  83]

sum of column: [ 81 121  55 201  85]
Count of negative: 13


In [40]:
supply=np.array(np.random.randint(20,80,(5,5)));
print(supply)
print()

demand=np.array(np.random.randint(20,80,(5,5)));
print(demand)
print()

Remaining_Stock=supply-demand;
print(Remaining_Stock)
d=np.where(Remaining_Stock<0,0,Remaining_Stock);
print()

print(d)
print()

cnt=0;
# e=np.where(Remaining_Stock<0,cnt=cnt+1,cnt=cnt+0);
cnt = np.sum(np.where(Remaining_Stock<=0,1,0))
# print(e)
print("\nNo. of products with shortage:", cnt)
print()
f=np.sort(Remaining_Stock,axis=0);
print(f)


[[21 64 69 74 47]
 [59 20 51 70 67]
 [36 40 37 31 42]
 [34 69 59 72 69]
 [73 50 27 45 44]]

[[66 42 21 79 31]
 [43 34 54 43 71]
 [78 56 51 78 54]
 [23 75 30 68 77]
 [64 58 42 51 52]]

[[-45  22  48  -5  16]
 [ 16 -14  -3  27  -4]
 [-42 -16 -14 -47 -12]
 [ 11  -6  29   4  -8]
 [  9  -8 -15  -6  -8]]

[[ 0 22 48  0 16]
 [16  0  0 27  0]
 [ 0  0  0  0  0]
 [11  0 29  4  0]
 [ 9  0  0  0  0]]


No. of products with shortage: 16

[[-45 -16 -15 -47 -12]
 [-42 -14 -14  -6  -8]
 [  9  -8  -3  -5  -8]
 [ 11  -6  29   4  -4]
 [ 16  22  48  27  16]]


In [49]:
import pandas as pd
df=pd.read_csv("./student_data.csv",sep=',')

print(df.head(10))
# head(number of row)
print()
print(df.tail())


   study_hours  attendance  sleep_hours  internet_usage  \
0            7          56            8               7   
1            4          69            5               3   
2           11          60            7               6   
3            8          99            9               8   
4            5          52            8               6   
5            7          40            9              10   
6           10          40            4              11   
7            3          86            7               3   
8            7          72            8               5   
9           11          77            4               9   

   assignments_completed  previous_score  exam_score placement_status  
0                     10              62      100.00           Placed  
1                      8              56      100.00           Placed  
2                     10              45      100.00           Placed  
3                      4              55       90.17          